package com.github.xiesen;

/**
 * Hello world!
 */
public class App {
    public static void main(String[] args) {
        String a = "{\"measures\":{},\"normalFields\":{\"message" +
                "\":\"ADZDJOCLBATAVRNNRXKPSEGZHLPOMUHJHAFQCARPKYJHXFOYNBBISHGOLNWGQIHMPCBYPRGSYAUGDNSSBAHCBHWZBTXAYFTTTZAGKOMOYKUOPAUHOUBDOVMDLORKPLXNHOYPAOQVXHTSTEOOHRRNJOMAFPKLDXRJIMSZVQASCQGKYMAGFJWOVHEFTUYEHUDGOZJXQABCGXSDOXRMKMWJGKRKZBSFAAANUYNYEXIKIKEVYNLJLZBMNPBHLTNOUBOOGGXVAHYPRJSXBLKHZNKHEWCQNCBWCXNYPICMQYFJOWMOYYBAXEUBNRUPYUJSKKOAYUYSVXJPRJRFUTVKMIYOELPNNGMIXVSOHUMOGYYCZFJIDAQARUZBUIJNHRRLEKGMVAYQIKZQAQNJCUWGBJHEDYESQQOIMSVFCOFZIMRCGPODGORPONGGDYVQWRUHPQPBXJGRWFFZNOACKIGIWCQDOCASZLSJYBZTORGPFKBEGTJLXMPZSWYPPJMGTZKAWOJNRYGFNHDWHHDVYQNRSPGVYNPKUZBJCOEFVTCVPOQUOYMRITRJEYCMAPYPJUKRRJFRSJKCOYSTLCRWGLDEMIUILHODWGNSVYHIKVXQEORFYQFFQYBKKDTCSPZABZZANPUKBLDBYUMNOMRVNPNOVBHNGXXDDXYQTXBRPCGBBMGVXGLYQHVNTXQRRCUKLWUUMCOFWEBZXFBXGWEVKTYCNLANFBYRDWXJRPIX\",\"countryCode\":\"BH\"},\"offset\":\"1082\",\"logTypeName\":\"streamx_log_avro\",\"source\":\"/var/log/xiesen.log\",\"timestamp\":\"2020-07-21T19:24:41.309+08:00\",\"dimensions\":{\"appsystem\":\"tdx6\",\"hostname\":\"zorkdata6\",\"appprogramname\":\"tc50\",\"ip\":\"192.168.1.6\"}}\n";
        System.out.println("Hello World!");
        System.out.println(a);
    }
}
